version: '3'
services:
  node:
    build: .
    container_name: node
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 3000:3000
    command: npm run dev
  rabbitmq:
    image: rabbitmq
    container_name: rabbit
    ports:
      - 5672:5672
